# Generated by Django 3.2.2 on 2021-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='my_image')),
                ('date', models.DateField(auto_now_add=True)),
                ('uploader', models.CharField(max_length=70)),
            ],
        ),
    ]
